server "157.245.189.199", user: "app", roles: %w[refresher]
# server "refresher2.feedbin", user: "app", roles: %w[refresher]
# server "refresher3.feedbin", user: "app", roles: %w[refresher]
# server "refresher4.feedbin", user: "app", roles: %w[refresher]
# server "refresher5.feedbin", user: "app", roles: %w[refresher]
# server "refresher6.feedbin", user: "app", roles: %w[refresher]
